baseURL: https://trebllaw.xyz
languageCode: en-us
title: "trebllaw"
theme: "toha"

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Meta description for your site.  This will help the search engines to find your site.
  description: Landing page for Wallbert Elicot.

  # background image of the landing page
  background: "images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /assets/images/main-logo.png
    inverted: /assets/images/inverted-logo.png
    favicon: /assets/images/favicon.png

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: Photos
    url: https://photos.trebllaw.xyz

  # some information about you
  author:
    name: "Wallbert Elicot"
    nickname: "Don"
    image: "images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "wall.elicot@trebllaw.xyz"
      phone: "+12092330088"
    # a summary of what you do
    summary:
    - I am a hobbyist Photographer
    - I enjoy technology
    - I love to read!
    - I wish to have more tattoos!
